module NinjaHelper
  module Generators
    class InstallGenerator < Rails::Generators::Base

      desc <<DESC
Description:
Copy ninja_helper and NinjaScript files to your application.
DESC

      def self.source_root
        @source_root ||= File.expand_path(File.join(File.dirname(__FILE__), 'templates'))
      end

      def copy_files
        directory 'images',     :destination => 'public/'
        directory 'javascripts', :destination => 'public/'
        directory 'stylesheets', :destination => 'public/'
      end

      def add_javascript
        file = File.join("public", "javascripts", "application.js")
        append_to_file(file) do
          <<ADDITIONAL_JS
Ninja.behavior({
  // Generated by ninja_helper install script
  // This line enables the NH behavior of graceful degradation of method links
  // to forms and back again
  '.ninja.graceful_form': Ninja.becomesLink
})
ADDITIONAL_JS
        end
      end

    end
  end
end
