module Mizugumo
  module Generators
    class InstallGenerator < Rails::Generators::Base

      desc <<DESC
Description:
Copy mizugumo and NinjaScript files to your application.
DESC

      def self.source_root
        @source_root ||= File.expand_path(File.join(File.dirname(__FILE__), 'templates'))
      end

      def copy_files
        directory 'images',     'public/images'
        directory 'javascripts', 'public/javascripts'
        directory 'stylesheets', 'public/stylesheets'
      end

      def add_javascript
        file = File.join("public", "javascripts", "application.js")
        append_to_file(file) do
          <<ADDITIONAL_JS
Ninja.behavior({
  // Generated by mizugumo install script
  // This line enables the NH behavior of graceful degradation of method links
  // to forms and back again
  '.mizugumo.graceful_form': Ninja.becomesLink
})
ADDITIONAL_JS
        end
      end

      def reminder
        say (<<NOTICE

Mizugumo is installed!
Remember to remove the default JS and link to the jQuery/NinjaScript
script and CSS files by adding these to your application layout:

  <%= stylesheet_link_tag 'mizugumo.css' %>
  <%= javascript_include_tag 'jquery-1.4.2.js' %>
  <%= javascript_include_tag 'jquery.ninja_script.js' %>
  <%= javascript_include_tag 'application.js' %>

If you want to use the Mizugumo AJAX scaffold generators, add this to your application.rb:

  config.generators do |g|
    g.scaffold_controller 'mizugumo:scaffold_controller'
    g.template_engine 'mizugumo:erb'
    # g.template_engine 'mizugumo:haml' # If you prefer Haml over ERB
  end

NOTICE
        )
      end
    end
  end
end
