module Mizugumo
  module Generators
    class InstallGenerator < Rails::Generators::Base

      desc <<DESC
Description:
Copy mizugumo and NinjaScript files to your application.
DESC

      def self.source_root
        @source_root ||= File.expand_path(File.join(File.dirname(__FILE__), 'templates'))
      end

      def copy_files
        if Mizugumo::RAILS_31
          directory 'images',      'app/assets/images'
          directory 'javascripts', 'app/assets/javascripts'
          directory 'stylesheets', 'app/assets/stylesheets'
        else          
          directory 'images',     'public/images'
          directory 'javascripts', 'public/javascripts'
          directory 'stylesheets', 'public/stylesheets'
        end
      end

      def add_javascript
        if Mizugumo::RAILS_31
          file = File.join("app", "assets", "javascripts", "mizugumo.js")
          create_file(file)
        else
          file = File.join("public", "javascripts", "application.js")
        end
        append_to_file(file) do
          <<ADDITIONAL_JS

// Generated by mizugumo install script
Ninja.orders(function(Ninja){
  Ninja.behavior({
    // This line enables the NS behavior of graceful degradation of method links
    // to forms and back again
    '.mizugumo_graceful_form': Ninja.becomesAjaxLink
  });
  Ninja.go();
})
ADDITIONAL_JS
        end
      end

      def reminder
        if Mizugumo::RAILS_31
          say (<<NOTICE )

Mizugumo is installed!

Javascript files have been added to your app/assets/javascripts directory.   You may need to check them for compatibility with your
other JS files. 

A few default style rules have been added as well as app/assets/stylesheets/mizugumo.sass.
NOTICE
        else
          say (<<NOTICE

Mizugumo is installed!
Remember to remove the default JS and link to the jQuery/NinjaScript script and CSS files by adding these to your application layout.  Note: it is important that ninjascript load after jquery, but before your application.js or any mizugumo-related code you write!

  <%= stylesheet_link_tag 'mizugumo.css' %>
  <%= javascript_include_tag 'jquery-1.6.4.min.js' %>
  <%= javascript_include_tag 'ninjascript.js' %>
  <%= javascript_include_tag 'rails.js' %>
  <%= javascript_include_tag 'application.js' %>

The included rails.js is a jQuery compatible implementation of rails.js, and should replace the default rails.js.
If you want to use the Mizugumo AJAX scaffold generators, add this to your application.rb:

  config.generators do |g|
    g.scaffold_controller 'mizugumo:scaffold_controller'
    g.template_engine 'mizugumo:erb'
    # g.template_engine 'mizugumo:haml' # If you prefer Haml over ERB
  end

NOTICE
        )
        end
      end
    end
  end
end
